# Generated by Django 6.1.2 on 2026-10-08 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina', models.CharField(max_length=100, verbose_name='máquina')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertas',
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina', models.CharField(max_length=100, verbose_name='máquina')),
                ('inicio', models.DateTimeField(verbose_name='inicio')),
                ('fin', models.DateTimeField(verbose_name='finalización')),
                ('motivo', models.TextField(verbose_name='motivo')),
                ('cancelada_en', models.DateTimeField(blank=True, null=True, verbose_name='cancelada en')),
                ('motivo_cancelacion', models.TextField(blank=True, null=True, verbose_name='motivo de cancelación')),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paradas_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='cancelada por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'parada',
                'verbose_name_plural': 'paradas',
                'ordering': ['-inicio', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fin__gt', models.F('inicio'))), name='parada_fin_posterior_al_inicio'), models.CheckConstraint(condition=models.Q(models.Q(('cancelada_en__isnull', True), ('cancelada_por__isnull', True), ('motivo_cancelacion__isnull', True)), models.Q(('cancelada_en__isnull', False), ('cancelada_por__isnull', False), ('motivo_cancelacion__isnull', False)), _connector='OR'), name='parada_cancelacion_completa_o_vacia')],
            },
        ),
    ]
