# Generated by Django 6.1.2 on 2026-10-08 17:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{7,15}$', 'El teléfono debe tener entre 7 y 15 dígitos.')], verbose_name='teléfono')),
                ('cedula', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6,12}$', 'La cédula debe tener entre 6 y 12 dígitos.')], verbose_name='cédula')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
            },
        ),
    ]
